name: new_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0
  shared_preferences: ^2.3.2
  fluttertoast: ^9.0.0
  provider: ^6.1.2
  ionicons: ^0.2.2
  carousel_slider: ^5.1.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
